esp_toml_version = 1.0
firmware_images_url = "https://raw.githubusercontent.com/PumpkinLin314/aec_test_firmware/refs/heads/main/"

supported_apps = ["aec_test_firmware"]

[aec_test_firmware]
readme.text = "https://raw.githubusercontent.com/PumpkinLin314/aec_test_firmware/refs/heads/main/README.md"
description = "AEC test firmware"
image.esp32s3_r2 = "aec_test_firmware-esp32s3_r2.bin"
image.esp32s3_r8 = "aec_test_firmware-esp32s3_r8.bin"
chipsets = ["esp32s3"]
developKits.esp32s3 = ["esp32s3_r2", "esp32s3_r8"]
